### PR TITLE
Libpitt/101 dsg

### PR DESCRIPTION
**Pull request by libpitt**
Change log:
1. Copy SeNet Doc's src folder to mimic functionality
2. Add data-submission-guide submodule

@tjmadonna @maxsibilla 
Need help with the github actions bit.

### CODE REVIEW

**Comment by maxsibilla** [comment]
@yuanzhou I have added you a reviewer as this PR does create a new method of generating a table of contents for each page (this is a new addition for the HuBMAP doc site). I have checked out various pages but its hard to determine if there is anything wrong as I am not as familiar with this site. 

To test this make sure to run ` git submodule update --init --remote`.

**Review by maxsibilla — APPROVED** [review]

**Comment by tjmadonna** [comment]
I also updated the Github Action on `data-submission-guide` to include `hubmapconsortium/software-docs`. This action sends an event to the docs repositories when `data-submission-guide` gets updated.

https://github.com/x-atlas-consortia/data_submission_guide/blob/main/.github/workflows/dispatch.yaml

**Comment by yuanzhou** [comment]
Thanks @tjmadonna, that's great!

**Comment by maxsibilla** [comment]
@shirey This latest commit should handle everything we discussed. See links locally:
http://localhost:4000/data-submission/Section1
http://localhost:4000/assays/wgs

**Pull request merged**
