### PR TITLE
port portal-docs

### PR DESCRIPTION
**Pull request by mccalluc**
Bring over all the content from https://github.com/hubmapconsortium/portal-docs, and add yaml frontmatter (so jekyll will process it). (With the exception of glossary.md, which was an empty stub.)

As noted before
- #5
- #6
- #9

there is no coherent structure here: I am just moving the files, and I hope the documentation team will address these problems

### CODE REVIEW

**Comment by mccalluc** [comment]
When this is merged, should review if there have been any late changes to [portal-docs](https://github.com/hubmapconsortium/portal-docs/commits/main) and integrate them as well.

**Review by shirey — CHANGES_REQUESTED** [review]
@mccalluc  
  - In the about.md/html page there is a snipit of HTML that is rendering as text between the "Team" heading and the table below.  Please fix.
  - The link to donor page on metadata.md/html is broken.
  - All of the assays/*.md pages have lost their styling.  I know how to fix, let me know if you want me to PR to this branch or fix directly in this branch.

**Comment by mccalluc** [comment]
The documentation team needs to take responsibility for fixing the documentation.

**Comment by mccalluc** [comment]
Comments addressed; Markdown tweaks made to handle differences between engines.

**Review by shirey — APPROVED** [review]
Looks good. Thanks for doing this, @mccalluc

**Pull request merged**
